### ISSUE TITLE
Buildbot does not instantiate slaves in parallel.

### ISSUE THREAD

**Issue by dinatale2** [opensfs/buildbot#4]
Buildbot seems to sequentially instantiate slaves when starting new builds. Looking through the code, it appears that they attempted to put the EC2 instantiate code in a separate thread. From what I can recall, after issuing a build to a builder, the buildbot master will sit and wait for a response from the slave before continuing forward and spinning up other slaves.

I'd have to dig into the code again to propose a solution. But, just so we don't lose track of this problem, I am creating this issue.

**Comment by morrone** [comment]
I'm working on this one at the moment.

**Comment by morrone** [comment]
I'm at least on the right path.  I have a very small patch that allows the substantiations and builds to start in parallel.  The major question about functionality though is in the error path, so I'll need to work on testing that an seeing if all is well there.

I also note that buildbot is often, but not always, choosing to substantiate a new slave rather than using an available idle one.  I don't yet know if that is related to my patch at all, or just something it does (and should be fixed).

**Comment by dinatale2** [comment]
The default behavior for buildbot is to choose a slave at random. So, it doesn't matter if there is an idle one or not. Buildbot blindly chooses. If you assign a builder a new nextslave function, then you can have custom functionality (i.e. pick the idle build slave).

**Comment by morrone** [comment]
Ah, great!  Then at least that part isn't a bug.  I'll set up a smarter nextslave function and continue testing.

**Comment by morrone** [comment]
I pushed a port of my patch to the upstream builbot repo here:

https://github.com/buildbot/buildbot/pull/2155

I got a quick response saying that there is a better fix under way.  We'll see how easy it will be to adapt for the eight branch.

**Comment by dinatale2** [comment]
Would you like me to apply this change to the master as a temporary fix?

**Comment by morrone** [comment]
OK, I'm going to land my patch as a temporary workaround.  It hasn't caused Brian any significant new issues with ZFSonLinux.  Longer term tomprince is working on larger architectural changes that will better address this issue for buildbot nine.  But there is no telling how long that will take to be released, and backports may not be reasonable.
